Hot Reload
CoEDL/elpis-gui pull request #91
Opened 2020-08-23 02:19 UTC by jdcaperon

2020-09-07 00:58 UTC, jdcaperon commented on src/components/Engine/SelectEngine.js
> +                        {useEffect(engineList)}
@benfoley

2020-09-07 01:11 UTC, benfoley commented on src/components/Engine/SelectEngine.js
> +                        {useEffect(engineList)}
Maybe pull the latest? `useEffect` was moved out of the `return`

2020-09-28 03:48 UTC, nicklambourne approved these changes

2020-09-28 03:58 UTC, nicklambourne requested changes
Can you merge master into this (and elpis proper). While the hot-reloading aspect appears to work, the interface is broken and file processing appears to fail.

2020-10-10 13:51 UTC, nicklambourne approved these changes

2020-10-14 21:25 UTC, merged